config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  scope "admin" do
    get "transactions" => "admin#transactions", as: :admin
    get "pending" => "accounts#pending", as: :pending_account
    patch "accounts/:id/approve" => "accounts#approve", as: :approve_account
    resources :accounts
  end

  scope "traders" do
    resources :stocks, only: [:new]
    get "portfolio" => "traders#portfolio", as: :traders_portfolio
    get "trending_stocks" => "traders#trending_stocks", as: :trending_stocks
    get "transactions" => "traders#transactions", as: :trader_transactions
    post "stocks" => "stocks#search", as: :search_stock
    get "stocks/:symbol" => "stocks#show", as: :stock
    get "stocks/:symbol/buy" => "transactions#buy_stock", as: :buy_stock
    get "stocks/:symbol/sell" => "transactions#sell_stock", as: :sell_stock
    post "stocks/:symbol" => "transactions#save_transaction", as: :save_transaction
  end

end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
  before_action :initialize_iex_client
  before_action :authorize_trader

  def portfolio
    @user_stocks = current_user.user_stocks.where("quantity > ?", 0)

    begin
      @quotes = @user_stocks.map { |user_stock| @client.quote(user_stock.stock.symbol)}
    rescue IEX::Errors::SymbolNotFoundError
      flash[:danger] = "Symbol not found. Please input a valid symbol."
      render :new
    end

    @total_amount = 0
    @user_stocks.each_with_index { |stock, i| @total_amount += stock.quantity * @quotes[i].latest_price}
  end

  def trending_stocks
    @trending_stocks = @client.stock_market_list(:mostactive)
  end

  def transactions
    @transactions = current_user.transactions.order(created_at: :desc)
  end

end

app/helpers/traders_helper.rb
module TradersHelper
end

app/views/traders/portfolio.html.erb
<div class="container mt-4">
    <div class="row d-flex justify-content-center border px-4 py-4 rounded-4 bg-light">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-auto">
                    <h1 class="fw-bold">My Portfolio</h1>
                </div>
                <div class="col-md-auto">
                    <%= link_to "Search New Stock", new_stock_path, class: "fw-bold btn btn-primary"%>
                </div>
                <div class="col text-end fs-2 fw-semibold">
                    Total: $<%= @total_amount.round(2) %>
                </div>
                <hr/>
            </div>
        </div>
        <table class="table table-hover align-middle">
            <thead>
                <tr>
                    <th scope="col">Symbol</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="text-center">Shares</th>
                    <th scope="col" class="text-center">Latest Price</th>
                    <th scope="col" class="text-center">Total Amount</th>
                    <th scope="col" class="text-center">Change %</th>
                    <th scope="col" colspan=3></th>
                </tr>
            </thead>
            <tbody>
                <% @user_stocks.each_with_index do |user_stock, i| %>
                    <tr>
                        <th scope="row">
                            <%= link_to user_stock.stock.symbol, search_stock_path(symbol: user_stock.stock.symbol), data: { turbo_method: "post" } %>
                        </th>
                        <td><%= user_stock.stock.name %></td>
                        <td class="text-center"><%= user_stock.quantity %></td>
                        <td class="text-center">$<%= @quotes[i].latest_price %></td>
                        <td class="text-center">$<%= (user_stock.quantity * @quotes[i].latest_price).round(2) %></td>
                        <% if @quotes[i].change_percent_s.start_with? '+' %>
                            <td class="text-center text-success"><%= @quotes[i].change_percent_s %><td>
                        <% else %>
                            <td class="text-center text-danger"><%= @quotes[i].change_percent_s %><td>
                        <% end %>
                        <td><%= link_to "Buy", buy_stock_path(user_stock.stock.symbol), class: "fw-semibold btn btn-success" %></td>
                        <td><%= link_to "Sell", sell_stock_path(user_stock.stock.symbol), class: "fw-semibold btn btn-danger" %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/traders/transactions.html.erb
<div class="container mt-4">
<div class="row d-flex justify-content-center border px-4 py-4 rounded-4 bg-light">

<h1 class="fw-bold">My Transactions</h1>
<hr/>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col" class="text-center">Stock</th>
            <th scope="col" class="text-center">Shares</th>
            <th scope="col" class="text-center">Price/Share</th>
            <th scope="col" class="text-center">Total Amount</th>
            <th scope="col" class="text-center">Type</th>
        </tr>
    </thead>
    <tbody>
        <% @transactions.each do |transaction| %>
            <tr>
                <td><%= transaction.created_at.in_time_zone('Singapore').strftime("%b %d, %Y @ %l:%M %p") %></td>
                <td class="text-center"><%= transaction.stock.symbol %></td>
                <td class="text-center"><%= transaction.quantity %></td>
                <td class="text-center">$<%= transaction.price %></td>
                <td class="text-center">$<%= transaction.amount %></td>
                <% if transaction.buy? %>
                    <td class="text-center text-success"><%= transaction.kind %></td>
                <% else %>
                    <td class="text-center text-danger"><%= transaction.kind %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

</div>
</div>

app/views/traders/trending_stocks.html.erb
<div class="container mt-4">
<div class="row d-flex justify-content-center border px-4 py-4 rounded-4 bg-light">

<h1 class="fw-bold">Trending Stocks</h1>
<hr/>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Symbol</th>
            <th scope="col">Name</th>
            <th scope="col" class="text-center">Latest Price</th>
            <th scope="col" class="text-center">Change</th>
        </tr>
    </thead>
    <tbody>
        <% @trending_stocks.each do |stock| %>
            <tr>
                <th scope="row">
                    <%= link_to stock.symbol, search_stock_path(symbol: stock.symbol), data: { turbo_method: "post" } %>
                </th>
                <td><%= stock.company_name %></td>
                <td class="text-center">$<%= stock.latest_price %></td>
                <% if stock.change_percent_s.start_with? '+' %>
                    <td class="text-center text-success"><%= stock.change_percent_s %><td>
                <% else %>
                    <td class="text-center text-danger"><%= stock.change_percent_s %><td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

</div>
</div>