config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  scope "admin" do
    get "transactions" => "admin#transactions", as: :admin
    get "pending" => "accounts#pending", as: :pending_account
    patch "accounts/:id/approve" => "accounts#approve", as: :approve_account
    resources :accounts
  end

  scope "traders" do
    resources :stocks, only: [:new]
    get "portfolio" => "traders#portfolio", as: :traders_portfolio
    get "trending_stocks" => "traders#trending_stocks", as: :trending_stocks
    get "transactions" => "traders#transactions", as: :trader_transactions
    post "stocks" => "stocks#search", as: :search_stock
    get "stocks/:symbol" => "stocks#show", as: :stock
    get "stocks/:symbol/buy" => "transactions#buy_stock", as: :buy_stock
    get "stocks/:symbol/sell" => "transactions#sell_stock", as: :sell_stock
    post "stocks/:symbol" => "transactions#save_transaction", as: :save_transaction
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :authorize_trader
    before_action :set_stock
    before_action :initialize_iex_client, except: [:save_transaction]
    before_action :get_quote, except: [:save_transaction]

    def buy_stock
        @transaction = Transaction.new
    end

    def sell_stock
        @transaction = Transaction.new
        @user_stock = current_user.user_stocks.find_or_initialize_by(stock: @stock)
    end

    def save_transaction
        @transaction = current_user.transactions.build(transaction_params)
        @transaction.amount = @transaction.calculate_amount

        @user_stock = current_user.user_stocks.find_or_create_by(stock: @stock)
        new_quantity = @transaction.calculate_new_quantity(@user_stock.quantity)

        if @transaction.save && @user_stock.update(stock: @stock, quantity: new_quantity)
            flash[:success] = "You successfully #{@transaction.buy? ? 'bought' : 'sold'} #{@transaction.quantity} share#{'s' if @transaction.quantity > 1} of #{@stock.symbol} stock!"
            redirect_to stock_path(@stock.symbol)
        else
            if @transaction.buy?
                redirect_to :buy_stock
            else
                redirect_to :sell_stock
            end
        end
    end

    private
        def transaction_params
            params.require(:transaction).permit(:kind, :quantity, :price, :stock_id)
        end

        def set_stock
            @stock = Stock.find_by(symbol: params[:symbol])
        end

        def get_quote
            @quote = @client.quote(@stock.symbol)
        end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_transaction_form.html.erb
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-4">
            <div class="border rounded-4 bg-light px-4 py-4" id="form1">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-auto text-center">
                        <h1 class="fw-bold"><%= stock.symbol %></h1>
                    </div>
                </div>
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-auto text-center">
                        <h5><%= stock.name %></h5>
                    </div>
                </div>

                <hr/>

                <%= form_with(scope: @transaction, url: save_transaction_path) do |f| %>
                    <%= f.hidden_field :stock_id, value: stock.id %>
                    <%= f.hidden_field :kind, {value: kind} %>
                    <%= f.hidden_field :price, value: @quote.latest_price %>
                    <div class="row g-3 align-items-center justify-content-center">
                        <div class="col-auto">
                            <span class="fs-4 fw-semibold">Price: $<%= @quote.latest_price %></span>
                        </div>
                    </div>

                    <div class="form-outline mb-4">
                        <div class="row g-3 align-items-center justify-content-center">
                            <div class="col-auto">
                                <%= f.label :quantity, "Quantity:", class: "form-label fs-4 fw-semibold" %>
                            </div>
                            <div class="col">
                                <%= f.number_field :quantity, class: "form-control fs-4", min: 1, value: 1, max: max_shares, required: true%>
                            </div>
                        </div>
                    </div>

                    <div class="col text-center d-grid gap-2 col-4 mx-auto">
                        <%= f.submit label, class: "fw-semibold btn #{kind == "buy" ? 'btn-success' : 'btn-danger'}" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/transactions/buy_stock.html.erb
<%= render "transaction_form", stock: @stock, kind: "buy", label: "Buy Stock", max_shares: "none" %>

app/views/transactions/sell_stock.html.erb
<%= render "transaction_form", stock: @stock, kind: "sell", label: "Sell Stock", max_shares: @user_stock.quantity %>