config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  scope "admin" do
    get "transactions" => "admin#transactions", as: :admin
    get "pending" => "accounts#pending", as: :pending_account
    patch "accounts/:id/approve" => "accounts#approve", as: :approve_account
    resources :accounts
  end

  scope "traders" do
    resources :stocks, only: [:new]
    get "portfolio" => "traders#portfolio", as: :traders_portfolio
    get "trending_stocks" => "traders#trending_stocks", as: :trending_stocks
    get "transactions" => "traders#transactions", as: :trader_transactions
    post "stocks" => "stocks#search", as: :search_stock
    get "stocks/:symbol" => "stocks#show", as: :stock
    get "stocks/:symbol/buy" => "transactions#buy_stock", as: :buy_stock
    get "stocks/:symbol/sell" => "transactions#sell_stock", as: :sell_stock
    post "stocks/:symbol" => "transactions#save_transaction", as: :save_transaction
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    private
        def authorize_admin
            render status: 401 unless current_user.admin
        end

        def authorize_trader
            render status: 401 if current_user.admin
        end

        def initialize_iex_client
            @client = IEX::Api::Client.new
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg sticky-top" id="header">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
        <% if current_user.try(:admin?) %>
            <%= link_to "TradeX", accounts_path, class: "navbar-brand text-light fw-bold" %>
        <% else %>
            <%= link_to "TradeX", traders_portfolio_path, class: "navbar-brand text-light fw-bold" %>
        <% end %>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
            <% if current_user.try(:admin?) %>
                <li class="nav-item">
                    <%= link_to "Transactions", admin_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                <%= link_to "Pending Accounts", pending_account_path, class: "nav-link text-light" %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Portfolio", traders_portfolio_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Transactions", trader_transactions_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Trending", trending_stocks_path, class: "nav-link text-light" %>
                </li>
            <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to edit_user_registration_path, class: "nav-link text-light"  do %>
                <%= current_user.email %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
            </li>
        <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-light" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log In", new_user_session_path, class: "nav-link text-light" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>