config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  scope "admin" do
    get "transactions" => "admin#transactions", as: :admin
    get "pending" => "accounts#pending", as: :pending_account
    patch "accounts/:id/approve" => "accounts#approve", as: :approve_account
    resources :accounts
  end

  scope "traders" do
    resources :stocks, only: [:new]
    get "portfolio" => "traders#portfolio", as: :traders_portfolio
    get "trending_stocks" => "traders#trending_stocks", as: :trending_stocks
    get "transactions" => "traders#transactions", as: :trader_transactions
    post "stocks" => "stocks#search", as: :search_stock
    get "stocks/:symbol" => "stocks#show", as: :stock
    get "stocks/:symbol/buy" => "transactions#buy_stock", as: :buy_stock
    get "stocks/:symbol/sell" => "transactions#sell_stock", as: :sell_stock
    post "stocks/:symbol" => "transactions#save_transaction", as: :save_transaction
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authorize_admin
  before_action :set_account, only: [:show, :edit, :update, :destroy,:approve]

  def index
    @accounts = User.where(admin:false)
  end

  def show
  end

  def new
    @account = User.new
  end

  def create
    @account = User.new(account_params)
    @account.skip_confirmation!
    if @account.save
      redirect_to account_path(@account), notice: "Account successfully added"
    else
      render :new
    end

  end

  def edit
  end

  def update
    @account.skip_reconfirmation!
    if @account.update(account_params)
      redirect_to account_path(@account), notice: "Account successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_path, notice: "Account successfully deleted"
  end

  def pending
    @accounts = User.where(approved:false)
  end

  def approve
    @account.skip_confirmation!
    if @account.update(approved:true)
      UserMailer.with(user: @account).approved_email.deliver_later
      redirect_to account_path(@account), notice: "Account successfully approved"
    end
  end

  private

  def set_account
    @account = User.find(params[:id])
  end

  def account_params
    params.require(:user).permit(:email,:password, :approved, :password_confirmation)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<div class="container mt-5">
<div class="row d-flex justify-content-center">
<div class="col-md-6">
<div class="border rounded-4 bg-light px-4 py-4" id="form1">
<h1 class="fw-bold">Edit Trader Account</h1>
<hr/>
<%= form_with(scope: @account, url: account_path, method: 'put', data: { turbo: false }) do |f| %>

  <div class="form-outline mb-4">
    <%= f.label :email, class:"form-label" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", id:"form2Example1", class:"form-control" %>
    <% @account.errors.full_messages_for(:email).each do |message| %>
        <div class="error-msg" style="color:red;"><%= message %></div>
    <% end %>
  </div>

  <div class="form-outline mb-4">
    <%= f.check_box :approved %>
    <%= f.label "Approved?", class:"form-label" %>
  </div>

  <div class="d-grid gap-2 col-6 mx-auto">
    <%= f.submit "Submit", class:"btn btn-primary btn-block mb-4" %>
  </div>

<% end %>

</div>
</div>
</div>
</div>

app/views/accounts/index.html.erb
<div class="container mt-4">
<div class="row d-flex justify-content-center border px-4 py-4 rounded-4 bg-light">


<p>
<h1 class="fw-bold">All Accounts</h1>
<%= link_to "Create Account", new_account_path, class:"btn btn-primary" %>
</p>

<table class="table table-hover ">
    <thead>
    <tr>
    <th scope="col">Email</th>
    <th scope="col">Creation Date</th>
    <th scope="col">Status</th>
    </tr>
    </thead>
    <% @accounts.each do |account| %>
    <tr>
    <td><%= link_to account.email, account_path(account) %></td>
    <td><%= account.created_at.in_time_zone('Singapore').strftime("%b %d, %Y @ %l:%M %p") %></td>
    <td><% if account.approved? %><span>approved</span><% else %><span>pending</span><% end %></td>
    </tr>
    <% end %>
</table>

</div>
</div>

app/views/accounts/new.html.erb
<div class="container mt-5">
<div class="row d-flex justify-content-center">
<div class="col-md-6">
<div class="border rounded-4 bg-light px-4 py-4" id="form1">
<h1 class="fw-bold">New Trader Account</h1>
<hr/>
<%= form_with(scope: @account, url: accounts_path, data: { turbo: false }) do |f| %>

  <div class="form-outline mb-4">
    <%= f.label :email, class:"form-label" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", id:"form2Example1", class:"form-control" %>
  
    <% @account.errors.full_messages_for(:email).each do |message| %>
      <div class="error-msg" style="color:red;"><%= message %></div>
    <% end %>

  </div>


  <div class="form-outline mb-4">
    <%= f.label :password, class:"form-label" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, autocomplete: "new-password", id:"form2Exampl2", class:"form-control" %>

    <% @account.errors.full_messages_for(:password).each do |message| %>
      <div class="error-msg" style="color:red;"><%= message %></div>
    <% end %>

  </div>

  <div class="form-outline mb-4">
    <%= f.label :password_confirmation, class:"form-label" %>
    <%= f.password_field :password_confirmation, autocomplete: "new-password", id:"form2Example2", class:"form-control" %>
    <% @account.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div class="error-msg" style="color:red;"><%= message %></div>
    <% end %>
  
  </div>

  <div class="d-grid gap-2 col-6 mx-auto">
    <%= f.submit "Submit", class:"btn btn-primary btn-block mb-4" %>
  </div>
<% end %>

</div>
</div>
</div>
</div>

app/views/accounts/pending.html.erb
<div class="container mt-5">
<div class="row d-flex justify-content-center">
<div class="col-md-6">
<div class="row d-flex justify-content-center border px-4 py-4 rounded-4 bg-light">
<h1 class="fw-bold"> Pending Accounts</h1>
<hr/>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Email</th>
            <th scope="col">Action</th>
        </tr>
    <thead>
    <% @accounts.each do |account| %>

    <tr>
    <td><%= account.email %></td>
    <td><%= link_to "Approve", approve_account_path(account), data: { turbo_method: :patch }, class:"btn btn-success" %>
    </tr>

    <% end %>
</table>

</div>
</div>
</div>
</div>

app/views/accounts/show.html.erb
<div class="container mt-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="row d-flex justify-content-center border px-4 py-4 rounded-4 bg-light">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-md-auto">
                            <h1 class="fw-bold">Account Details</h1>
                        </div>
                        <div class="col-md-auto">
                            <%= link_to "Edit", edit_account_path(@account), class:"btn btn-warning" %>
                            <%= link_to "Delete", account_path(@account), data: { turbo_method: :delete, turbo_confirm: "Are you sure to proceed?" }, class:"btn btn-danger" %>
                        </div>
                    </div>
                    <hr/>
                </div>
                <table class="table">
                    <tr>
                        <td><b>Email:</b></td>
                        <td><%= @account.email %></td>
                    </tr>

                    <% if @account.approved? %>
                        <tr>
                            <td><b>Account Status:</b></td>
                            <td>Approved</td>
                        </tr>

                        <tr>
                        <td><b>Confirmation Status:</b></td>
                        <td><%= @account.confirmed_at.in_time_zone('Singapore').strftime("%b %d, %Y @ %l:%M %p") %></td>
                        </tr>

                    <% else %>
                        <tr>
                            <td><b>Account Status:</b></td>
                            <td>Pending</td>
                        </tr>

                        <tr>
                        <td><b>Confirmation Status:</b></td>
                        <td>
                            <% if @account.confirmed_at == nil %>
                                Unconfirmed
                            <% else %>
                                <%= @account.confirmed_at.in_time_zone('Singapore').strftime("%b %d, %Y @ %l:%M %p") %>
                            <% end %>
                        </td>
                        </tr>
                    <% end %>

                </table>

            </div>
        </div>
    </div>
</div>